spring:
  shardingsphere:
    datasource:
      names: ds1
      ds1:
        type: com.zaxxer.hikari.HikariDataSource
        driverClassName: com.mysql.cj.jdbc.Driver
        jdbcUrl: jdbc:mysql://csi-tools-dev-dbmysql.hic.cloud:3306/z_cjl_test_db?characterEncoding=utf8&autoReconnect=true&useSSL=false&serverTimezone=GMT
        username: csi-vuln-service_rw
        password: UU85U0MteV
    sharding:
      tables:
        tb_device:
          actual-data-nodes: ds1.tb_device_$->{0..1}
          table-strategy: # 如果没有inline插入会两个表都插入
            inline:
              sharding-column: device_id
              algorithm-expression: tb_device_$->{device_id%2}
        tb_device_info:
          actual-data-nodes: ds1.tb_device_info_$->{0..1}
          table-strategy:
            inline:
              sharding-column: device_id
              algorithm-expression: tb_device_info_$->{device_id%2}
        tb_device_type:
          keygenerator:
            column: type_id
            type: SNOWFLAKE
      binding-tables: #防止多表的表join查询 笛卡尔积，数组形式   也可以 binding-tables[0]: tb_device,tb_device_info
        - tb_device,tb_device_info
#      broadcast-tables: tb_device_type
    props:
      sql:
        show: true
